package main

import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
func compute(limit int) int64 {
	f1, f2, sum := 1, 1, int64(0)
	var fn int
	for i := 3; i <= limit; i++ {
		fn = f1 + f2
		if fn > limit {
			break
		}
		if fn%2 == 0 {
			sum += int64(fn)
		}
		f1 = f2
		f2 = fn
	}
	return sum
}

func main() {
	fmt.Println(compute(4_000_000))
}
