package main

import "fmt"

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle T_n,=n(n+1)/2 1,3,6,10,15,...
Pentagonal P_n, = n(3n —1)/2 1,5,12,22,35,...
Hexagonal H_n=n(2n—1) 1,6, 15,28,45,...

It can be verified that T_285 = P_165 = H_143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
*/
func main() {
	gonalNumbers := map[int64]int{}

	for i := int64(300); i <= 100_000; i++ {
		triangle := i * (i + 1) / 2
		pentagon := i * (3*i - 1) / 2
		hexagon := i * (2*i - 1)

		gonalNumbers[triangle]++
		gonalNumbers[pentagon]++
		gonalNumbers[hexagon]++
	}

	for index, val := range gonalNumbers {
		if val == 3 {
			fmt.Println(index)
		}
	}
}
