package main

import (
	"fmt"
	"math/big"
)

/*
How many distinct terms are in the sequence generated by a^b for 2<=a<=100 and 2<=b<=100?
*/
func compute(n int) int {
	s := map[string]bool{}
	for a := 2; a <= n; a++ {
		for b := 2; b <= n; b++ {
			bigA := big.NewInt(int64(a))
			bigB := big.NewInt(int64(b))
			pow := bigA.Exp(bigA, bigB, nil)
			s[pow.String()] = true
		}
	}
	return len(s)
}

func main() {
	fmt.Println(compute(100))
}
