package main

import (
	"fmt"
	"os"
)

/*
Pentagonal numbers are generated by the formula, n(3n-1)/2. The first ten pentagonal numbers are:

	1,5,12,22,35,51,70,92,117,145,

It can be seen that P_4+P_7=22+70=92=P_8. However, their difference, P_7 - P_4, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?
*/
func main() {

	pentagons := map[int]bool{}
	for n := 1; n <= 10_000; n++ {
		pentagon := n * (3*n - 1) / 2
		pentagons[pentagon] = true
	}

	for p := range pentagons {
		for q := range pentagons {
			if p <= q {
				sum := p + q
				_, sumPentagonal := pentagons[sum]
				if sumPentagonal {
					diff := q - p
					_, diffPentagonal := pentagons[diff]
					if diffPentagonal {
						fmt.Println(diff)
						os.Exit(0)
					}
				}
			}
		}
	}

}
